const features = [
  {
    title: 'AI Match Insights',
    desc: 'Get a deep understanding of your performance through AI-driven match analysis that reveals key moments, decision-making, and win conditions.',
    icon: 'assets/icon/Go_On,_Impress_Me!_Emote.png',
  },
  {
    title: 'Champion Performance',
    desc: 'Track your most played champions, strengths, and weaknesses. See detailed stats that go beyond the scoreboard.',
    icon: 'assets/icon/Level_500_Prestige_Emote.png',
  },
  {
    title: 'Personalized Coaching',
    desc: 'Receive tailored improvement suggestions generated by AI, helping you focus on what matters most to climb the ladder.',
    icon: 'assets/icon/2024_-_Split_1_-_Victorious_Anivia_Emote.png',
  },
];

export default function FeaturesSection() {
  return (
    <section className="bg-gray-950 text-white px-4 sm:px-6 lg:px-8 py-28 w-full relative overflow-hidden">
      <div className="max-w-6xl mx-auto text-center mb-16">
        <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight text-primary mb-4">
          What Makes LoLo Powerful
        </h2>
        <p className="text-gray-400 text-base sm:text-lg max-w-2xl mx-auto">
          LoLo uses state-of-the-art AI to break down every aspect of your gameplay. Understand,
          adapt, and evolve faster than ever.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
        {features.map((feat) => (
          <div
            key={feat.title}
            className="relative bg-black border-2 border-white px-6 py-8 sm:px-8 sm:py-10 shadow-[4px_4px_0_0_#ffffff] hover:shadow-[2px_2px_0_0_#ffffff] transition-all duration-200 mx-2"
          >
            <div className="text-4xl sm:text-5xl mb-6 flex justify-center">
              <img src={feat.icon} alt="Icon" />
            </div>
            <h3 className="text-xl sm:text-2xl font-bold mb-3 text-center">{feat.title}</h3>
            <p className="text-gray-400 leading-relaxed text-sm sm:text-base">{feat.desc}</p>
          </div>
        ))}
      </div>

      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(255,255,255,0.05),transparent_70%)] pointer-events-none"></div>
    </section>
  );
}
